services:
  web:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    name: mongo-data
